
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-courses-s26-04
owner: ucsb-cs156-s26
repo_name: proj-courses-s26-04
pull_requests: [{"author":{"id":"U_kgDOCeRyWA","is_bot":false,"login":"Ertan10","name":"Ertan"},"headRefName":"ertan-issue7-legacy","number":40,"title":"Replaces Whitelabel Error Page with more user friendly custom error page","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-04/pull/40"},{"author":{"id":"U_kgDOCM7v4A","is_bot":false,"login":"t-ladha","name":""},"headRefName":"tl-validateQTRs","number":39,"title":"Validate the values of START_QTR and END_QTR","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-04/pull/39"},{"author":{"id":"U_kgDOBuiegQ","is_bot":false,"login":"ErikRodriguez29","name":""},"headRefName":"35-coursedescriptionsearch-add-course-description-to-the-table","number":36,"title":"CourseDescriptionSearch: Add Course Description to the table","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-04/pull/36"}]
